sudo: required
language: node_js

node_js:
  - "node"
  - "8"
  - "6"

env:
  - CXX=g++-4.8
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libusb-1.0-0-dev
      - libudev-dev
      - libpcap-dev
      - g++-4.8
   
before_install:
  - npm install -g node-gyp
